
import pandas as pd
import numpy as np
import os

# --- 데이터 생성 ---
np.random.seed(42)
n_samples = 100

# 그룹 A (기존 디자인)
group_a = pd.DataFrame({
    'group': 'A',
    'time_on_site': np.random.normal(loc=120, scale=30, size=n_samples).clip(10) # 평균 120초
})

# 그룹 B (새로운 디자인)
group_b = pd.DataFrame({
    'group': 'B',
    'time_on_site': np.random.normal(loc=135, scale=35, size=n_samples).clip(10) # 평균 135초 (개선)
})

# 데이터 합치기
df = pd.concat([group_a, group_b], ignore_index=True)

# CSV 문자열로 변환 (줄바꿈 문자를 \n으로 일관되게 처리)
csv_data = df.to_csv(index=False).replace('\r\n', '\n')

# TypeScript 파일로 저장할 경로 설정
output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'lib', 'example-datasets')
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, 'ab-test-data.ts')

# TypeScript 파일 내용 생성
ts_content = f'// This file is auto-generated by a script. Do not edit.\nexport const abTestData = `{csv_data}`.trim();'

# 파일에 쓰기
# 스크립트 실행 시마다 항상 최신 데이터로 덮어쓰도록 로직 단순화
try:
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(ts_content)
    print(f"Successfully generated/updated A/B test data at '{output_path}'.")
except Exception as e:
    print(f"Error writing to file '{output_path}': {e}")

